#!/usr/bin/env python3
"""Export questionnaire display metadata to explicitly selected frontends."""

from __future__ import annotations

import argparse
import json
import os
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BACKEND = ROOT / "backend"
CATALOG = BACKEND / "domain" / "questionnaire_routes.json"
DATA_DIR = BACKEND / "questionnaire_data"
FRONTEND_TARGET = ROOT / "frontend" / "src" / "data" / "questionnaireRoutes.js"
FRONTEND_V2_TARGET = (
    ROOT / "frontend-v2" / "packages" / "shared" / "src" / "data" / "questionnaireRoutes.js"
)


def render_payload(catalog_path: Path = CATALOG, data_dir: Path = DATA_DIR) -> str:
    catalog_document = json.loads(catalog_path.read_text(encoding="utf-8"))
    catalog = catalog_document["routes"]
    labels = {route: item["label"] for route, item in catalog.items()}
    keywords = {route: item["keywords"] for route, item in catalog.items()}
    fields = {}
    field_labels = {}
    for route in catalog:
        document = json.loads((data_dir / f"{route}.json").read_text(encoding="utf-8"))
        fields[route] = [question["field"] for question in document["questions"]]
        field_labels[route] = {
            question["field"]: question["prompt"].rstrip(" *") for question in document["questions"]
        }
    return (
        "// Generated by backend/scripts/export_questionnaire_frontend.py.\n"
        "export const QUESTIONNAIRE_ROUTE_LABELS = "
        + json.dumps(labels, ensure_ascii=False, indent=2)
        + "\n\nexport const QUESTIONNAIRE_ROUTE_KEYWORDS = "
        + json.dumps(keywords, ensure_ascii=False, indent=2)
        + "\n\nexport const QUESTIONNAIRE_ROUTE_FIELDS = "
        + json.dumps(fields, ensure_ascii=False, indent=2)
        + "\n\nexport const QUESTIONNAIRE_FIELD_LABELS = "
        + json.dumps(field_labels, ensure_ascii=False, indent=2)
        + "\n"
    )


def selected_targets(*, include_frontend_v2: bool) -> tuple[Path, ...]:
    targets = [FRONTEND_TARGET]
    if include_frontend_v2:
        targets.append(FRONTEND_V2_TARGET)
    return tuple(targets)


def _atomic_write_text(path: Path, payload: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temporary_path = Path(handle.name)
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_path, path)
    finally:
        if temporary_path is not None and temporary_path.exists():
            temporary_path.unlink()


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def export_payload(payload: str, targets: tuple[Path, ...], *, check: bool) -> bool:
    drifted = []
    for target in targets:
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current == payload:
            print(f"OK {_display_path(target)}")
            continue
        if check:
            drifted.append(target)
            print(f"DRIFT {_display_path(target)}")
            continue
        _atomic_write_text(target, payload)
        print(f"WROTE {_display_path(target)}")
    return not drifted


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--frontend-v2",
        action="store_true",
        help="also update the separately controlled production frontend",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="report generated-file drift without writing files",
    )
    args = parser.parse_args(argv)
    payload = render_payload()
    targets = selected_targets(include_frontend_v2=args.frontend_v2)
    return 0 if export_payload(payload, targets, check=args.check) else 1


if __name__ == "__main__":
    raise SystemExit(main())
